### ISSUE TITLE
Same publicPath when loading images from css and html files

### ISSUE THREAD

**Issue by fredyrivas** [webpack-contrib/file-loader#272] opened 2018-04-24 16:44 UTC
The problem is that publicPath will always result on the same path. For images loaded from html will work ok, but when css is trying to load background images won't. because the css file is not at the same index.html level

Project structure: 

index.html
**css**/style.css
**img**/image1.jpg, image2.jpg

so this will work:

`<img src="img/image1.jpg">`

but this won't:

`body{ background-image: url("img/image2.jpg")}`

my loader looks like this: 

`
{

                test: /\.(jpg|png|gif)$/,
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 100000,
                        fallback: 'file-loader',
                        name: '[name].[ext]',
                        publicPath: 'assets/img/',
                        outputPath: 'assets/img/'
                    }
                }
            }`

Here is my [repo](https://github.com/fredyrivas/webpack-template)

**Comment by a-carvallo** [comment] 2018-04-26 15:18
I have more or less the same config, and the same problem.

It was working with 1.1.7 with the following options: 
```js
                options: {
                    name: '[name].[ext]',
                    useRelativePath: true,
                    outputPath: "img",
                    publicPath: ""
                }
```

**Comment by evilebottnawi** [comment] 2018-04-26 15:53
@a-carvallo why you remove `publicPath`?

**Comment by fredyrivas** [comment] 2018-04-26 16:34
@a-carvallo I ended up using other method to copy images files: [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin). So I only used file-loader for fonts. It's a way more simple way and you forget about relative or absolute paths. 
I guess url-loader will be the best option if you're looking for base64 images all bundle in your js file.

**Comment by a-carvallo** [comment] 2018-04-26 16:54
Hello @evilebottnawi,

You are right about `publicPath`, and I was missing a slash for the `outputPath`, but I still need `useRelativePath: true` (or else all links are only `name.ext`), so a valid 1.1.7 config for me is:

```js
                options: {
                    name: '[name].[ext]',
                    useRelativePath: true,
                    outputPath: "img/",
                }
```

But the problem is still here with version 1.1.11: the links in the css will be `img/name.ext` instead of `../img/name.ext`.
(And yes for 1.1.11, `useRelativePath: true` makes things worse.)

Also by reading about `useRelativePath` in the README, I do feel like I need it, maybe it's not behaving as it should.

@fredyrivas Well, good that you got it working that way. (Still, that's a workaround, not a fix :stuck_out_tongue:)

**Comment by evilebottnawi** [comment] 2018-04-26 17:04
@a-carvallo Don't use `useRelativePath`, it is very rare use case and i think i will be removed in next major version. `useRelativePath` !== `useRelativeURL` (many people think what it is same).

**Comment by evilebottnawi** [comment] 2018-04-26 17:07
One big note:
`outputPath` is place where your want to save files
`publicPath` is what url you have in `js`, `css` and etc files.

**Comment by evilebottnawi** [comment] 2018-04-26 17:09
Also you can look in source code and find what `useRelativePath` affected only on `outputPath`.

**Comment by a-carvallo** [comment] 2018-04-27 12:49
Hey @evilebottnawi, thanks for the answers, I did read them, and I did check the code.

> Don't use `useRelativePath`, it is very rare use case and i think it will be removed in next major version. `useRelativePath ` !== `useRelativeURL` (many people think what it is same), we don't have `useRelativeURL`. If you want relative url in you css this options don't help you.

I get it for `1.1.11`, but fact is it worked in `1.1.7` (Yes I know it was maybe an unwanted side-effect).
Maybe an option `useRelativeURL` would be nice then.

> One big note:
> `outputPath` is place where your want to save files
> `publicPath` is what url you have in `js`, `css` and etc files.

Yep these options are quite clear.

> Also you can look in source code and find what `useRelativePath` affected only on `outputPath`.

That's not totally true, if `publicPath` option is not defined it will use `outputPath` :
```js
var publicPath = `__webpack_public_path__ + ${JSON.stringify(outputPath)}`;
```

Back to the original topic, is it possible to obtain the same behaviour as `1.1.7` with `1.1.11` ?
If not, that's a real issue, considering it  doesn't look like a complex uncommon use case to me.

**Comment by evilebottnawi** [comment] 2018-04-27 12:52
@a-carvallo Why you need `useRelativePath`? What is you real use case?

**Comment by a-carvallo** [comment] 2018-04-27 13:04
@evilebottnawi 

To make it simple, I have : 
```
|   index.html
+---css
|       style.css
+---img
    |   image.jpg
```
In style.css:
`background: url("../img/image.jpg")`

In index.html:
`<img src="img/image.jpg">`

And I basically want the same in the output, but instead for the css I get:
`background: url("img/image.jpg")`

So it doesn't work because the css is not in the same folder as the index.html

**Comment by evilebottnawi** [comment] 2018-04-27 13:07
@a-carvallo Please read my notices, relative urls is out of scope `file-loader`, **it should be done by minifier/uglifier**. Main function `file-loader` is save file to fs and output public path to this asset and all. Change `url` in css should be done with `cssnano` or `csso`. Thanks!

**Comment by evilebottnawi** [comment] 2018-04-27 13:08
Also it can very expensive and very difficult because extract css can save file to any folder and normalize url should be done in end of build process.

**Comment by a-carvallo** [comment] 2018-04-27 13:33
@evilebottnawi 

Heh, thanks for being clear, even though it's a shame, guess I'll just stick with 1.1.7 for now.
Using a complete minifier just to have the right url in css seems a bit too much.

**Comment by evilebottnawi** [comment] 2018-04-27 13:44
@a-carvallo it is good practice for production mode, you don't do this development, because it is reduce build time. Also don't use old version `file-loader` it can break something in future and present for other plugins/loaders.

**Comment by a-carvallo** [comment] 2018-04-27 13:55
@evilebottnawi Thanks for the advice but I already spent too much time fighting with this :stuck_out_tongue:.

Not specific to file-loader but, it's kinda annoying to struggle with stuff like this, not actually doing progress on the real project, only trying to make project tools work.

**Comment by evilebottnawi** [comment] 2018-04-27 13:59
@a-carvallo `file-loader` should be simple and works with all types of assets, without options for `css/html/js` and etc. Normalize url as i say above should be done in optimize assets event, not in compile. Thanks for discussion.

**Comment by evilebottnawi** [comment] 2018-06-04 18:31
@fredyrivas friendly ping, problems still exists?

**Comment by fredyrivas** [comment] 2018-06-05 15:57
@evilebottnawi I really couldn't find a way to resolve paths but as you mentioned before this needs optimize assets event, and thats something I haven't try. Thanks for the follow up

**Comment by djsmit** [comment] 2018-09-26 14:56
> One big note:
> `outputPath` is place where your want to save files
> `publicPath` is what url you have in `js`, `css` and etc files.

After strolling all of the internet this is the first time I read a clear explanation. Thanks!

**Comment by andreyvolokitin** [comment] 2018-10-07 16:28
Same problem here. I thought that conditional `publicPath` could resolve this issue, but the `publicPath` function gets only file `url` as a sole parameter. I.e. if it would also receive a way to get a file from which this `url` was imported — then we could apply appropriate  `publicPath` (for files imported from `index.html` it would be empty string, so final file url would be `url` parameter as is; and for files imported from `css/style.css` it would be `../` so final file url would be `url` parameter prepended with `../`: `../url`). I also found a [PR](https://github.com/webpack-contrib/file-loader/pull/157) that suggests passing (wepback?) API as a second argument to the `publicPath` function but it stays unmerged for very long time

**Comment by andreyvolokitin** [comment] 2018-10-07 16:36
Also I'm not sure how css minifier can fix URLs but I will dig into it...

**Comment by andreyvolokitin** [comment] 2018-10-09 12:36
Possible solution using `mini-css-extract-plugin`: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/44#issuecomment-379059788

**Comment by mendoncanorma** [comment] 2018-12-10 06:16
publicPath in MiniCssExtractPlugin works provided we don't specify publicPath in file-loader.
file-loader publicPath overrides publicPath of MiniCssExtractPlugin.

@evilebottnawi ,
Can this be taken care?

**Comment by evilebottnawi** [comment] 2018-12-10 08:46
@mendoncanorma can you describe more verbosely, maybe with examples?

**Comment by mendoncanorma** [comment] 2018-12-10 09:44
This is my webpack file. Currently I am not using dev server.

```
const path                  = require('path');
const UglifyJSPlugin        = require('uglifyjs-webpack-plugin');
const MiniCssExtractPlugin  = require('mini-css-extract-plugin');
const CleanWebpackPlugin    = require('clean-webpack-plugin');

const publicPath = '';

module.exports = {
  entry: "./src/index.js",
  mode: "development",
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: "assets/js/[name].bundle.js",
    publicPath: publicPath
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              publicPath: '../../'
            }
          },
          {loader: 'css-loader'},
          {loader: 'sass-loader'}
        ]
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'assets/images/[name].[ext]'
            }
          }
        ]
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/env']
          }
        }
      }
    ]
  },
  plugins: [
    new UglifyJSPlugin(),
    new MiniCssExtractPlugin({
      filename: "assets/css/[name].css"
    })
  ]
};
```

This is my folder structure:

+---- dist/
 |--------index.html (static file)
+---- src/
 |--------images/
 |----------------start.png
 |----------------kiwi.jpg
 |--------index.js

After compiling, assets folder is created inside dist. 

+---- dist/
 |--------assets/
 |----------------css/
 |------------------------main.css
 |----------------images/
 |------------------------kiwi.jpg
 |------------------------star.png
 |----------------js/
 |------------------------main.bundle.js

To resolve the file path issue with background image in css file, I have provided publicPath for MiniCssExtractPlugin.loader and things work fine. 

Image file: `<img src="assets/images/kiwi.jpg" />`
CSS background image: `background: url(../../assets/images/star.png);`

Problem arises when I decide to have a folder htmlTemplate inside dist folder and move index.html inside it. Now the browser starts looking for kiwi.jpg inside dist/htmlTemplates/assets/ folder and hence 404. 

To solve this, I provided publicPath for file-loader
```

      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'assets/images/[name].[ext]',
              publicPath: '../'
            }
          }
        ]
      },

```
Image file: `<img src="../assets/images/kiwi.jpg" />`
CSS background image: `background: url(../assets/images/star.png);`

If you see, the background image path is rendered using publicPath of file-loader though I have specified publicPath under MiniCssExtractPlugin.loader.

**Comment by evilebottnawi** [comment] 2018-12-10 10:05
@fredyrivas thanks for reply, can you create minimum reporudicble test repo and desribe this in README? Easy debug and help, thanks!

**Comment by DarrieutortPierre** [comment] 2018-12-14 22:45
Hello, I had the same problem as you and I just solve it !

I keep the same options :
`test: /\.(png|jpg|gif|svg)$/i,
                use: [{
                        loader: 'url-loader',
                        options: {
                            limit: 8192,
                            name: '[name].[hash:7].[ext]',
                            outputPath: 'img/'
                        }
                    }`
Then i've saw the @mendoncanorma 's post and just had the following piece before the other and it's works fine for me :+1:  :
`{
                test: /\.(sa|sc|c)ss$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                        options: {
                            publicPath: '../' //? Relative path to style's URLs
                        }
                    },
                    ...cssLoaders,
                    'sass-loader'
                ]
            }`
I hope I've helped you !

PS : link to the webpack.config.js ==> [](https://gitlab.com/Pierre_Darrieutort/my-website/blob/master/webpack.config.js)

**Comment by Albosonic** [comment] 2018-12-16 21:39
Hi I had the same issue, when upgrading to webpack v4, finally solved it by using image-webpack-loader along with file-loader. I made a quick post about since I noticed I wasn't the only one:
https://medium.com/@albertomadueno/webpack-v4-config-d6cee480a071
also README here:
https://github.com/tcoopman/image-webpack-loader

**Comment by evilebottnawi** [comment] 2018-12-19 16:04
Problem was in `css-loader` and fixed in `2` version. Feel free to feedback

**Closed by evilebottnawi** 2018-12-19 16:04 UTC

**Comment by mustafawm** [comment] 2019-02-18 05:53
I am using MiniCssExtractPlugin.loader, setting its publicPath to one level up worked for me

```js
output: {
....
  publicPath: 'static/',
...
}

...
.....

    module: {
      rules: [
        {
          test: /\.(sc|c)ss$/,
          exclude: /\.module\.(sc|c)ss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
        {
          test: /\.module\.(sc|c)ss$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                publicPath: '../static/',  // <<------- here
              },
            },
            { loader: 'css-loader' },
            { loader: 'sass-loader' },
          ],
        },
      ],
    },
  });
```

**Comment by undeadborn** [comment] 2019-07-11 08:51
I faced this issue in a project with multiple entry points (not a SPA). They were sharing the same assets but having different relative paths to them. Project is deployed under a particular base context (http://localhost:8080/app), so using absolute path "/" as the publicPath was not an option.

The way I fixed it was putting all entries that were using assets on same directory level, so they will work with the same relative paths.

So the webpack output would be this:

```
|----index.html --> this redirects to one of the modules as a default
+----module1
|-------- index.html
+----module2
|-------- index.html
+----module3
|-------- index.html
+----scripts
|-------- common.js
|-------- vendors.js
|-------- module1.js
|-------- module2.js
|-------- module3.js
+----css
|-------- common.js
|-------- module1.css
|-------- module2.css
|-------- module3.css
+----images
|-------- img1.png
|-------- img2.png
...
```

Then on webpack config you setup paths this way:

```
output --> 
	filename --> 'scripts/[name].js'
	publicPath --> '/'
file-loader (images) --> 
	options --> 
		name --> '[name].[ext]'
		outputPath --> 'images/'
		publicPath --> '../images/'
MiniCssExtractPlugin -->
	filename --> 'css/[name].css'
```

Hope this helps to anyone having the same issue.

**Comment by ararename** [comment] 2019-12-05 19:34
Hello, i faced the same problem and in my case i was able to just split the source directories for my files like this: 
```
/img/
/img/background-img/
/img/regular-img/
```
According to the names images implemented as background images go into /img/background-img/ and regular ones go into /img/regular-img/. 

```
      {
        test: /\.(png|jp(e*)g|svg)$/,  
        include: /background-img/,
        use: [{
          loader: 'url-loader',
          options: { 
            limit: 10, // Convert images < 8kb to base64 strings
            emitFile: true,
            outputPath: './assets/img/',
            name: '[name].bg.[ext]',
            publicPath: '../../assets/img/' 
          } 
        }]
      },

      {
        test: /\.(png|jp(e*)g|svg)$/,
        include: /regular-img/,  
        use: [{
          loader: 'url-loader',
          options: { 
            limit: 10, // Convert images < 8kb to base64 strings
            emitFile: true,
            outputPath: './assets/img/',
            name: '[name].reg.[ext]',
            publicPath: 'assets/img/' 
          } 
        }]
      }
```
Later yet, but maybe it is useful to somebody.

**Comment by aldordar** [comment] 2020-11-16 10:52
Hi everyone! I have the same issue as @fredyrivas . Any update on the above? Thanks :)

**Comment by ZaidKhan144** [comment] 2021-01-07 17:42
After hours of googling, finally a thread that pulls me out of the mess. Thank y'all for sharing your insights/solutions.
